### PR TITLE
Re-apply customization to latest upstream master

### PR DESCRIPTION
**Pull request by enlight**
This re-applies all the customization currently in master to the new `loomchain` branch created from upstream revision `a4e6eebac93c60d80aa01a9f133d51b05aeb38d7`.

TODO:
- [x] Test locally. I think the idea is to use Docker to start a local Blockscout instance that's pointed at extdev (see `docker/README` in this branch). The customization has changed the frontend, and some of the backend services so:
   - [x] Check this PR actually builds.
   - [x] Check the frontend UI doesn't have any obvious bugs (QA can do more extensive testing once we deploy to asia1).
   - [x] Check that blocks & tx details are being fetched.
- [x] Test on asia1. We can re-index.
- [x] Figure out if/how we can migrate existing Blockscout DBs on extdev & Plasmachain to this new Blockscout version, worst case we just re-index everything. I believe there are migrations in this repo (see `apps/explorer/priv/repo/migrations`) but it's not clear if they'll run automatically or there's some command we need to use.

### CODE REVIEW

**Comment by atchapcyp** [comment]
When `make run`
```
Compiling 164 files (.ex)
Generating BlockScoutWeb.Cldr for 3 locales named ["en", "en-001", "root"] with a default locale named "en"
warning: function market_cap/2 is unused
  lib/block_scout_web/views/chain_view.ex:6

Compilation failed due to warnings while using the --warnings-as-errors option
The command '/bin/sh -c mix compile' returned a non-zero code: 1
make: *** [build] Error 1
```

**Comment by adyromantika** [comment]
The `ecto.migrate` is a separate command that we run when we launch the service, so we can probably try it without reindex first on asia1.

**Comment by adyromantika** [comment]
Last commit https://github.com/loomnetwork/blockscout/pull/70/commits/ce6f3422dd79334050915f3e7f8d3260a2d6202c was built and tagged as `customize2`

**Comment by adyromantika** [comment]
It is deployed to a temporary location at http://asia1-blockexplorer-testing.devdc.io/

Please let me know if we want to deploy it to the real asia1 blockexplorer.

**Pull request merged**
